group 'sq.flutter.tflite'
version '1.0-SNAPSHOT'

buildscript {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

apply plugin: 'com.android.library'

android {
    namespace 'sq.flutter.tflite'

    compileSdk 37

    defaultConfig {
        minSdk 19
        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'
    }

    lint {
        disable 'InvalidPackage'
    }

    dependencies {
        implementation 'com.google.ai.edge.litert:litert:2.2.0'
    }
}
